# Generated by Django 3.2.2 on 2021-07-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sscs', '0003_auto_20210603_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='nicknames',
        ),
        migrations.AddField(
            model_name='client',
            name='nicknames',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
