# Generated by Django 3.2.2 on 2021-07-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sscs', '0005_auto_20210706_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='date_of_first_visit',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='date_of_last_visit',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='household_size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='pets_cat_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='pets_dog_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
