# Generated by Django 3.2.5 on 2021-07-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sscs', '0006_auto_20210706_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='head_of_household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sscs.client'),
        ),
    ]
