# Generated by Django 3.2.5 on 2021-08-01 16:15

from django.db import migrations, models
import uuid


def add_uuid(apps, schema_editor):
    Client = apps.get_model('sscs', 'Client')
    for client in Client.objects.all():
        if not client.cid:
            client.cid = uuid.uuid4()
            client.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sscs', '0007_client_head_of_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(
            add_uuid,
            reverse_code=migrations.RunPython.noop,
            ),
        migrations.AlterField(
            model_name='client',
            name='cid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]
