# Generated by Django 3.2.7 on 2021-09-28 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sscs', '0008_client_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
